/**
 * Repli éditorial — ressources site public (aligné sur related_media Supabase).
 */
(function (global) {
  global.ResourcesData = {
    media_types: [
      { code: 'WEB', label: 'Lien web', sort_order: 5 },
      { code: 'PRESS', label: 'Article de presse', sort_order: 10 },
      { code: 'EXCAT', label: "Catalogue d'exposition", sort_order: 20 },
      { code: 'BOOK', label: 'Livre', sort_order: 30 },
      { code: 'VIDEO', label: 'Vidéo', sort_order: 40 },
      { code: 'AUDIO', label: 'Enregistrement audio', sort_order: 50 },
    ],
    items: [
      {
        id: 'c1000001-0000-4000-8000-000000000001',
        media_type_code: 'PRESS',
        title: 'Marie Sallantin met la pression',
        media_date: null,
        source: 'Sur la peinture',
        description: '',
        url: 'http://sur-la-peinture.com/marie-sallantin-met-la-pression/#more-6342',
        thumbnail_path: '',
        file_path: '',
        internal_path: '',
        duration_seconds: null,
        publication_status_code: 'W',
        sort_order: 10,
        is_essential: true,
        series_codes: [],
        work_ids: [],
      },
      {
        id: 'c1000002-0000-4000-8000-000000000002',
        media_type_code: 'WEB',
        title: 'Exposition à La Capitale Galerie',
        media_date: null,
        source: 'La Capitale Galerie',
        description: '',
        url: 'https://lacapitalegalerie.fr/marie-sallantin-2',
        thumbnail_path: '',
        file_path: '',
        internal_path: '',
        duration_seconds: null,
        publication_status_code: 'W',
        sort_order: 20,
        is_essential: false,
        series_codes: [],
        work_ids: [],
      },
      {
        id: 'c1000003-0000-4000-8000-000000000003',
        media_type_code: 'WEB',
        title: 'Galerie Peinture Fraîche',
        media_date: null,
        source: 'Galerie Peinture Fraîche',
        description: '',
        url: 'https://galeriepeinturefraiche.art/sallantin-marie',
        thumbnail_path: '',
        file_path: '',
        internal_path: '',
        duration_seconds: null,
        publication_status_code: 'W',
        sort_order: 30,
        is_essential: false,
        series_codes: [],
        work_ids: [],
      },
      {
        id: 'c1000004-0000-4000-8000-000000000004',
        media_type_code: 'VIDEO',
        title: 'Interview avec David Foenkinos',
        media_date: null,
        source: 'KTOTV',
        description: '',
        url: 'https://www.ktotv.com/video/00071872/david-foenkinos-et-marie-sallantin',
        thumbnail_path: '',
        file_path: '',
        internal_path: '',
        duration_seconds: null,
        publication_status_code: 'W',
        sort_order: 40,
        is_essential: true,
        series_codes: [],
        work_ids: [],
      },
      {
        id: 'c1000005-0000-4000-8000-000000000005',
        media_type_code: 'WEB',
        title: "Face à l'Art — salon virtuel de peintres",
        media_date: null,
        source: "Face à l'Art",
        description: '',
        url: '',
        thumbnail_path: 'images/logo-fap.jpg',
        file_path: '',
        internal_path: 'fap.html',
        duration_seconds: null,
        publication_status_code: 'W',
        sort_order: 50,
        is_essential: false,
        series_codes: [],
        work_ids: [],
      },
    ],
  };
})(typeof window !== 'undefined' ? window : globalThis);
